name: tests and style-check

on: [push, pull_request, workflow_dispatch]

jobs:

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: TillBrede/action-style@main
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Run Tests
        uses: TillBrede/action-test@main
