name: tests and style-check

on: [push, pull_request, workflow_dispatch]

jobs:

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: TillBrede/action-style@main
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout module
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Run tests 
        uses: TillBrede/action-tests@main

  test-legacy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout module
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install required PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3' #This version is currently used by Symcon | In later versions the tested wddx function is removed
      - name: Run tests 
        uses: TillBrede/action-test@main
        with:
          phpunit-version: '9.2.6'
